### ISSUE TITLE
about mat file

### ISSUE THREAD

**Issue by Zhi-Tu** [garyptchoi/rectangular-conformal-map#1]

**Comment by Zhi-Tu** [comment]
how to get a .mat file? and how to get the corner.

**Comment by garyptchoi** [comment]
The .mat file consists of the vertex coordinates v and triangulations f of a mesh. You can import meshes from other sources to MATLAB to get v and f. 
The four corner indices can either be specified by the user (by picking four vertices on the boundary of the input mesh) or automatically determined by the program.
